#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Autostart
$HOME/.config/bspwm/autostart.sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width	5
bspc config window_gap		10
bspc config top_padding		25

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Code desktop='^2' follow=on
bspc rule -a firefox desktop='^3' follow=on
bspc rule -a TelegramDesktop desktop='^4' follow=on state=floating
bspc rule -a discord desktop='^5' follow=on
bspc rule -a Spotify desktop='^6' follow=on
bspc rule -a Thunar desktop='^7' follow=on
bspc rule -a gwenview desktop='^8' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
